### ISSUE TITLE
Potential security breach.

### ISSUE THREAD

**Issue by agood-boy** [thibaudcolas/draftjs-conductor#145]
Potential security breach. Username and password in URI in Url in file [/.env.production](https://github.com/thibaudcolas/draftjs-conductor/tree/master/.env.production)

You should recycle your credenttials immediately and move secrets to environment variables to prevent them being committed to GitHub.

Hope this will be helpful to you！

shout me a coffee ☕️ via [PayPal](https://www.paypal.me/agoodboy)

<a href="https://www.paypal.me/agoodboy">
  <img width="160" height="41" src="https://raw.githubusercontent.com/DWilliames/paddy-sketch-plugin/master/.images/paypal-badge.png" >
</a>

**Comment by thibaudcolas** [comment]
There is no username nor password in this file. This file is meant for environment variables, and only contains publicly-available information.
