### ISSUE TITLE
Thank you!!

### ISSUE THREAD

**Issue by varunarora** [thibaudcolas/draftjs-conductor#286]
Thibaud, I just wanted to thank you for an excellent set of utilities! I was pretty surprised that my entities did not get carried when I cut or copy pasted atomic blocks from one Editor component to another. Your comments on issues in the main repo led me to your library, and I am grateful that using it was a breeze! I also found the solution pretty clever and smart (storing the serialized ContentState in the HTML clipboard contents).

Great job, and thanks again!!

**Comment by thibaudcolas** [comment]
Hey @varunarora, that’s lovely to hear :) Thank you

**Comment by andelkocvjetkovic** [comment]
a big thanks for this lib
