### ISSUE TITLE
Add test content to the demo site

### ISSUE THREAD

**Issue by thibaudcolas** [thibaudcolas/draftjs-conductor#6]
At the moment, the [demo site](https://thibaudcolas.github.io/draftjs-conductor/) shows two editors, but they are empty by default. There should be test content in at least one of them so people have an easier time understanding what the project is about.

- [ ] Add test content for infinite list nesting to one editor
- [ ] Add another editor with test content for copy-paste idempotency

**Comment by aulisius** [comment]
Hey!

I'd like to work on this.

> Add another editor with test content for copy-paste idempotency

What exactly do you mean by this?

**Comment by thibaudcolas** [comment]
Hey @aulisius, nice! 🙂 

The "test content for copy-paste idempotency" would be test content for https://github.com/thibaudcolas/draftjs-conductor#idempotent-copy-paste-between-editors – so for example an image or links in the content.

If you want to work on this, test content for the lists alone would already be super nice.

**Comment by aulisius** [comment]
Ah, got it!. I had a doubt, how exactly do I start up the demo site though? I wasn't able to figure out any pointers to setting up the demo site for development.

**Comment by thibaudcolas** [comment]
Here are the instructions: https://github.com/thibaudcolas/draftjs-conductor/blob/master/.github/CONTRIBUTING.md#contribution-guidelines. Once you've done the initial setup, `npm run start` is the one.

**Comment by thibaudcolas** [comment]
:tada: This issue is fixed in v0.4.4, available on npm: [draftjs-conductor@0.4.4](https://www.npmjs.com/package/draftjs-conductor).

<p align="right">
Generated by :package::rocket: <a href="https://github.com/semantic-release/semantic-release">semantic-release</a>
</p>
